<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0
 * FormDin Version: 4.2.6-alpha
 * 
 * System ap2v created in: 2018-11-21 23:30:54
 */

class Acesso {

	public function __construct(){
    }    

	//--------------------------------------------------------------------------------	
	public static function login( $login_user, $pwd_user )	{
        $result = null;
		$user = UsuarioDAO::selectByLogin($login_user);
        if (password_verify($pwd_user, $user['DSSENHA'][0])) {
            $_SESSION[APLICATIVO]['USER']['IDUSUARIO'] = $user['IDUSUARIO'][0];
            $_SESSION[APLICATIVO]['USER']['LOGIN']  = $login_user;
            $_SESSION[APLICATIVO]['USER']['NOME']  = $user['NMUSUARIO'][0];
            $result = 1;
        } else {
            $result = 0;
        }
        return $result;
    }

    public static function getUserId()	{
        $userId = null;
        if (ArrayHelper::has(APLICATIVO, $_SESSION)) {
            $user = ArrayHelper::get($_SESSION[APLICATIVO],'USER');
            $userId = $user['IDUSUARIO']; 
        }
        return $userId;
    }
    
    public static function getUserLogin() {
        $userLogin = null;
        if (ArrayHelper::has(APLICATIVO, $_SESSION)) {
            $user = ArrayHelper::get($_SESSION[APLICATIVO],'USER');
            $userLogin = $user['LOGIN'];
        }
        return $userLogin;
    }

    public static function getUserName() {
        $userName = null;
        if (ArrayHelper::has(APLICATIVO, $_SESSION)) {
            $user = ArrayHelper::get($_SESSION[APLICATIVO],'USER');
            $userName = $user['NOME'];
        }
        return $userName;
    }

	public static function isUserLoggedAdm(){
        $result = false;     
        if (self::getUserLogin() == 'admin') {
            $result = true;
        }
        return $result;
    }
}
?>