<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.0.0
 * FormDin Version: 4.2.10-alpha
 * 
 * System seadra created in: 2019-02-10 19:58:02
 */

if ( !function_exists( 'seadra_autoload') ) {
	function seadra_autoload( $class_name )	{
		require_once $class_name . '.class.php';
	}
spl_autoload_register('seadra_autoload');
}