<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.0.0
 * FormDin Version: 4.3.1-alpha
 * 
 * System seadra created in: 2019-03-09 11:50:59
 */

class Configuracao {

	public function __construct(){
	}
	//--------------------------------------------------------------------------------
	public static function selectById( $id ){
		return ConfiguracaoDAO::selectById( $id );
	}
	//--------------------------------------------------------------------------------
	public static function selectCount( $where=null ){
		return ConfiguracaoDAO::selectCount( $where );
	}
	//--------------------------------------------------------------------------------
	public static function selectAllPagination( $orderBy=null,$where=null,$page=null,$rowsPerPage= null ){
		return ConfiguracaoDAO::selectAllPagination( $orderBy,$where,$page,$rowsPerPage );
	}
	//--------------------------------------------------------------------------------
	public static function selectAll( $orderBy=null,$where=null ){
		return ConfiguracaoDAO::selectAll( $orderBy,$where );
	}
	//--------------------------------------------------------------------------------
	public static function save( ConfiguracaoVO $objVo ){
		$result = null;
		if ( $objVo->getIdconfiguracao() ){
			$result = ConfiguracaoDAO::update( $objVo );
		} else {
			//$result = ConfiguracaoDAO::insert( $objVo );
		}
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function delete( $id ){
		//return ConfiguracaoDAO::delete( $id );
	}
	//--------------------------------------------------------------------------------
}
?>