<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.0.0
 * FormDin Version: 4.2.12-alpha
 * 
 * System seadra created in: 2019-02-15 23:59:32
 */

class Itempedido {

	public function __construct(){
	}
	//--------------------------------------------------------------------------------
	public static function selectById( $id ){
		return ItempedidoDAO::selectById( $id );
	}
	//--------------------------------------------------------------------------------
	public static function selectCount( $where=null ){
		return ItempedidoDAO::selectCount( $where );
	}
	//--------------------------------------------------------------------------------
	public static function selectAllPagination( $orderBy=null,$where=null,$page=null,$rowsPerPage=null ){
		return ItempedidoDAO::selectAllPagination( $orderBy,$where,$page,$rowsPerPage );
	}
	//--------------------------------------------------------------------------------
	public static function selectAll( $orderBy=null,$where=null ){
		return ItempedidoDAO::selectAll( $orderBy,$where );
	}
	//--------------------------------------------------------------------------------
	public static function selectItensMaisVendidos(){
		return ItempedidoDAO::selectItensMaisVendidos();
	}
	//--------------------------------------------------------------------------------
	public static function save( ItempedidoVO $objVo ){
		$result = null;
		if( $objVo->getIditempedido() ) {
			$result = ItempedidoDAO::update( $objVo );
		} else {
			self::validar( $objVo );
			$result = ItempedidoDAO::insert( $objVo );
		}
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function delete( $id ){
		return ItempedidoDAO::delete( $id );
	}
	//--------------------------------------------------------------------------------
    private static function validar( ItempedidoVO $objVo ){
        self::validarItemCadastrado( $objVo );
	}
	//--------------------------------------------------------------------------------
    private static function validarItemCadastrado( ItempedidoVO $objVo ){
        $where = array( 'IDPEDIDO'=>$objVo->getIdpedido(),'IDPRODUTO'=>$objVo->getIdproduto() );
        $dados = self::selectAll( null,$where );
        if( !empty($dados) ){
            throw new DomainException( Mensagem::PRODUTO_JA_CADASTRADO ); 
        }
    }
	//--------------------------------------------------------------------------------
}
?>