<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.0.0
 * FormDin Version: 4.2.12-alpha
 * 
 * System seadra created in: 2019-02-15 23:59:32
 */

class Itempedido {

	public function __construct(){
	}
	//--------------------------------------------------------------------------------
	public static function selectById( $id ){
		return ItempedidoDAO::selectById( $id );
	}
	//--------------------------------------------------------------------------------
	public static function selectCount( $where=null ){
		return ItempedidoDAO::selectCount( $where );
	}
	//--------------------------------------------------------------------------------
	public static function selectAllPagination( $orderBy=null,$where=null,$page=null,$rowsPerPage=null ){
		return ItempedidoDAO::selectAllPagination( $orderBy,$where,$page,$rowsPerPage );
	}
	//--------------------------------------------------------------------------------
	public static function selectAll( $orderBy=null,$where=null ){
		return ItempedidoDAO::selectAll( $orderBy,$where );
	}
	//--------------------------------------------------------------------------------
	public static function save( ItempedidoVO $objVo ){
		$result = null;
		if( $objVo->getIditempedido() ) {
			$result = ItempedidoDAO::update( $objVo );
		} else {
			$result = ItempedidoDAO::insert( $objVo );
		}
		if ($result) {
			$idPedido = $objVo->getIdpedido();
			$idUsuario = $objVo->getIdusuario();
			$result = PedidoDAO::updateValores( $idPedido,$idUsuario );
		}
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function delete( $id ){
		return ItempedidoDAO::delete( $id );
	}
	//--------------------------------------------------------------------------------
}
?>