<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0
 * FormDin Version: 4.2.7-alpha
 * 
 * System seadra created in: 2018-12-03 21:17:31
 */

$perfilBancoAdm  = ServidorConfig::getInstancia()->getPerfilAdm();

define('BANCO'   , $perfilBancoAdm['dbms']);
define('HOST'    , $perfilBancoAdm['hostname']);
define('PORT'    , $perfilBancoAdm['port']);
define('DATABASE', $perfilBancoAdm['dbname']);
define('SCHEMA'  , '');
define('USUARIO' , $perfilBancoAdm['username']);
define('SENHA'   , $perfilBancoAdm['password']);
define('UTF8_DECODE'   , 0);
?>