<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0
 * FormDin Version: 4.2.6-alpha
 * 
 * System seadra created in: 2018-11-25 11:19:56
 */

define('BANCO'   , 'MYSQL');
define('HOST'    , 'localhost');
define('PORT'    , '3306');
define('DATABASE', 'seadra');
define('SCHEMA'  , '');
define('USUARIO' , 'root');
define('SENHA'   , '');
define('UTF8_DECODE'   , 0);
?>