<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0
 * FormDin Version: 4.2.6-alpha
 * 
 * System seadra created in: 2018-11-25 11:19:56
 */

define('SYSTEM_NAME'    , 'Seadra');
define('SYSTEM_ACRONYM' , 'seadra');
define('SYSTEM_VERSION' , '1.0.0');
define('APLICATIVO'     , SYSTEM_ACRONYM);
define('DS'   , DIRECTORY_SEPARATOR);
?>