<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0
 * FormDin Version: 4.2.7-alpha
 * 
 * System seadra created in: 2018-12-03 21:17:31
 */

$ambiente  = ServidorConfig::getInstancia()->getConfigParam('ambiente');
if ( $ambiente == 'produção' || $ambiente == 'producao' ){
    $ambiente = null;
}
$sigla = ServidorConfig::getInstancia()->getConfigParam('sigla');
$cssFile = ServidorConfig::getInstancia()->getConfigParam('cssfile');
$customMenu = ServidorConfig::getInstancia()->getConfigParam('custommenu');

define('SYSTEM_NAME'       , 'Seadra');
define('SYSTEM_NAME_SUB'   , $ambiente);
define('SYSTEM_ACRONYM'    , 'seadra');
define('SYSTEM_VERSION'    , '0.1.0');
define('SYSTEM_SIGLA'      , $sigla);
define('APLICATIVO'        , SYSTEM_ACRONYM);
define('STATUS_ATIVO'      , 'S');
define('STATUS_INATIVO'    , 'N');
define('LINHAS_POR_PAGINA' , 15);
define('CSS_FILE'          , $cssFile);
define('CUSTOM_MENU'       , $customMenu);

if (!defined('DS')) define('DS', DIRECTORY_SEPARATOR);
?>