<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0-alpha
 * FormDin Version: 4.2.6-alpha
 * 
 * System seadra created in: 2018-11-15 14:42:51
 */

$menu = new TMenuDhtmlx();
$menu->add('1', null, 'Menu', null, null, 'menu-alt-512.png');
$menu->add('1.0',1,'cliente','modulos/cliente.php');
$menu->add('1.1',1,'pedido','modulos/pedido.php');
$menu->add('1.2',1,'produto','modulos/produto.php');
$menu->add('1.3',1,'usuario','modulos/usuario.php');
$menu->add('9', null, 'Sobre', 'modulos/sys_about.php', null, 'information-circle.jpg');

$menu->add('10',null,'Config Ambiente',null,null,'setting-gear-512.png');
$menu->add('10.1','10','Ambiente Resumido','modulos/sys_environment_summary.php',null,'information-circle.jpg');
$menu->add('10.2','10','PHPInfo','modulos/sys_environment.php',null,'php_logo.png');
$menu->add('10.4','10','Gerador VO/DAO','../base/includes/gerador_vo_dao.php');
$menu->add('10.5','10','Gerador Form VO/DAO','../base/includes/gerador_form_vo_dao.php',null,'smiley-1-512.png');
$menu->getXml();
?>